services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    # Not giving envfile for now
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # TODO: Look at Traefik 
  # TODO: https://fastapi.tiangolo.com/deployment/docker/#behind-a-tls-termination-proxy
  proxy:
    # This is currently broken, but my desktop runs it normally. Why?
    # image: nginx:stable
    # volumes:
    #   - ./assets/nginx/nginx.http.config:/etc/nginx/nginx.conf
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    restart: on-failure:5

  backend-migrate:
    command: bash -c "cd app/ && alembic upgrade head"
    build:
      context: .
      dockerfile: backend.dockerfile
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
