services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    # Not giving envfile for now
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # TODO: Look at Traefik 
  # TODO: https://fastapi.tiangolo.com/deployment/docker/#behind-a-tls-termination-proxy
  proxy:
    image: nginx:latest
    volumes:
      - ./assets/nginx/nginx.http.config:/etc/nginx/nginx.conf
    #   #- ./assets/nginx/certs:/etc/nginx/certs
    #   - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure:5

  backend-migrate:
    command:  bash -c "cd app/ && alembic upgrade head"
    build:
      context: .
      dockerfile: backend.dockerfile
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started